openapi: 3.0.3
info:
  title: Document Reader
  description: |-
    This is a Spring Boot Camunda Application based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io).
  termsOfService: https://swagger.io/terms/
  contact:
    email: Jan
  version: '@project.version@'
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
servers:
  - url: http://localhost:8080
tags:
  - name: config
    description: Providing of application configuration for the frontend.

paths:
  /document/upload:
    post:
      tags:
        - document
      operationId: uploadDocument
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/DocumentUploadRequest'
      description: Upload file server
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartList'
components:
  schemas:
    DocumentUploadRequest:
      type: object
      properties:
        file:
          type: string
          format: binary
        schema:
          type: string
          description: Your expected json schema. Add descriptions to properties to increase result
      required:
        - file
        - schema
    Part:
      type: object
      properties:
        partNumber:
          type: string
          description: The unique identifier of the part
        manufacturer:
          type: string
          description: The name of the manufacturer
        serialNumber:
          type: string
          description: The serial number of the part
      required:
        - partNumber
        - manufacturer
        - serialNumber
      additionalProperties: false
    PartList:
      type: object
      properties:
        parts:
          type: array
          items:
            $ref: '#/components/schemas/Part'
      required:
        - parts
      additionalProperties: false


