tldr:
  resource-url: classpath:/sample1.pdf
  tessdata-path: /opt/homebrew/share/tessdata
  tessdata-language: deu
  prompt-template: |
    Extract data. The table headers are "Part Number", "Serial Number" and "Manufacturer". "Serial Number" can be a UUID. If a line only contains one hexadecimal string and no other tokens, it is the final part of the serial number from the previous line. null missing values.
    
    Input:
      {{document}}

spring:
  config:
    import: optional:file:.env[.properties]
  threads:
    virtual:
      enabled: true
  application:
    name: Ai PDF and Image Data Reader
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      organization-id: ${OPENAI_ORG_ID}
      project-id: ${OPENAI_PROJECT_ID}

      # chat options will be overridden by environment variables if set
      chat:
        options:
          model: gpt-4.1-mini
          temperature: 0
          top_p: 1
management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus

logging:
  level:
    org.springframework.ai: ERROR